name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Test
      run: go test -v -race ./...
    - name: Check Go generate
      run: set -ue; go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=app/config.yaml app/app.yaml; git diff --quiet || { echo "run 'go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=app/config.yaml app/app.yaml'"; exit 1; }
