name: Lint OpenAPI Specs

on: [push, pull_request]

jobs:
  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint OpenAPI specs
        uses: docker://redocly/cli:latest
        with:
          args: -lint --format github-actions
