name: Lint OpenAPI Specs

on: [push, pull_request]

jobs:
  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nwestfall/openapi-action@v1.0.2
        with:
          file: app/app.yaml
